-define(SAMPLE_SUIT, [{6, clubs}, {7, clubs}, {8, clubs}, {10, clubs}]).
-define(MANY_SEQUENCES, [{6, clubs}, {7, clubs}, {8, clubs}, {10, clubs}, {11, clubs}, {12, clubs}]).
-define(LONG_SEQUENCE, [{6, clubs}, {7, clubs}, {8, clubs}, {9, clubs}, {12, clubs}, {10, clubs}]).
-define(SAMPLE_HAND, [{6, clubs}, {7, clubs}, {11, spades}, {13, spades}, {12, spades}, {9, clubs}, {10, hearts}, {10, clubs}]).
-define(MULTIPLE_SEQUENCES, [{7, clubs}, {7, diamonds}, {8, clubs}, {8, diamonds}, {9, clubs}, {9, diamonds}]).
-define(TALON, [{13, hearts}, {14, hearts}, {10, spades}, {11, clubs}, {14, spades}, {7, diamonds}, {8, diamonds}]).
